version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./photo_aggr:/docker-entrypoint-initdb.d/photo_aggr

  api_server:
    build:
      context: .
      dockerfile: Dockerfile.api_server
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"
      MONGO_INITDB_DATABASE: "photo_aggr"
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb
    restart: on-failure

volumes:
  pgdata:
  mongo-data:
